# ------ Default 
weight_decay: 5.0e-4
decay_type: "cosine"
use_amp: True        # Use automatic mixed precision
epochs: 90
lr : 1.0e-3
seed : 0
warmup_steps : 100
random_seed : 0
# ------ Dataset
dataset: 'cifar100'
train_batch_size: 64
test_batch_size: 64
pin_memory : True
num_classes : 100
img_size : 224
data_mean : [0.5, 0.5, 0.5]
data_std : [0.5, 0.5, 0.5]
num_workers : 8


# Validation Setting"""
interval_val : 1 

# Save Path"""
ckpt_fpath : '../experiments/DPSGD/cifar100'

# WANDB SETTINGS"""
wandb:
  project : 'DPSGD'
  id : 'jonggyujang0123'
  name : 'ResNet50_lr'
  active : True
