# ------ Default 
weight_decay: 5.0e-4
decay_type: "cosine"
use_amp: False        # Use automatic mixed precision
epochs: 100
lr : 3.0e-3
seed : 0
n_z : 2
warmup_steps : 100
random_seed : 0
beta : 0.5
# ------ Dataset
dataset: 'mnist'
img_size : 28
train_batch_size: 128
test_batch_size: 256
pin_memory : True
data_mean : [0.5]
data_std : [0.5]
#data_mean : [0.5, 0.5, 0.5]
#data_std : [0.5, 0.5, 0.5]
num_workers : 8


# Validation Setting"""
interval_val : 1 

# Save Path"""
ckpt_fpath : '../experiments/VAE/mnist'

# WANDB SETTINGS"""
wandb:
  project : 'VAE'
  id : 'jonggyujang0123'
  name : 'VAE_lr'
  active: True
