# ------ Default 
weight_decay: 5.0e-4
decay_type: "cosine"
use_amp: False        # Use automatic mixed precision
epochs: 20
lr : 1.0e-4
seed : 0
n_z : 100
n_gf : 64
n_df : 64
warmup_steps : 100
random_seed : 0
beta : 0.5
# ------ Dataset
dataset: 'celebA'
img_size : 64
train_batch_size: 256
test_batch_size: 16
pin_memory : True
data_mean : [0.5, 0.5, 0.5]
data_std : [0.5, 0.5, 0.5]
num_workers : 8


# Validation Setting"""
interval_val : 1 

# Save Path"""
ckpt_fpath : '../experiments/DCGAN/celebA'

# WANDB SETTINGS"""
wandb:
  project : 'DCGAN'
  id : 'jonggyujang0123'
  name : 'DCGAN_lr'
  active : True
